name: Deploy simple

on:
  workflow_dispatch:
    inputs:
      destination_env:
        description: 'To which MultiDev environment do you wish to deploy? (m1-m10)'
        required: true
        default: 'm1'
      clone_env:
        description: 'From which other Pantheon environment shall we clone the database and files? (dev, test, live, m1-m10)'
        required: true
        default: 'dev'

env:
  php_version: '7.4'
  pantheon_env: ${{ github.event.inputs.destination_env }}
  pantheon_repo: ${{ secrets.PANTHEON_REPO }}
  pantheon_site_name: ${{ secrets.PANTHEON_SITE_NAME }}

jobs:

  deploy:
    name: Simple workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate PWD
        run: pwd
