name: Deploy to Pantheon
on:
  push:
    branches:
      - 'dev-build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        github_repo: '${{ secrets.GHUB_REPO }}'
      run: |
        echo "repo :: ${{ secrets.PANTHEON_REPO }}" . $pantheon_repo
        echo "keys2 :: ${{ secrets.PANTHEON_SSH_KEY2 }}" . $key
        eval `ssh-agent -s` ssh-add - <<< '${{ secrets.PANTHEON_SSH_KEY2  }}'
        git remote add pantheon $pantheon_repo
        git push -f pantheon HEAD:master
